#Imagen que voy a utilizar como base
FROM python:3.8.16-alpine

WORKDIR /usr/src/app

COPY app/vote/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app/vote .

EXPOSE 80

CMD ["python3", "./app.py"]