version: '3'
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - app_net
  app:
    container_name: app
    image: hegelberkeley/app_redis:1.0.0
    restart: always
    ports:
      - 8080:80
    networks:
      - app_net
    depends_on:
      - redis
networks:
  app_net: