#Imagen que voy a utilizar como base
FROM nginx:alpine

#Etiquetado
LABEL project="buscaminas"

COPY ./app/. /usr/share/nginx/html
#Como metadato, indicamos que el contenedor utiliza el puerto 80
EXPOSE 80

CMD ["nginx","-g","daemon off;"]