#Imagen que voy a utilizar como base
FROM php:7.4-apache

# Instalar el módulo mysqli
RUN docker-php-ext-install mysqli

#Environment variables to configure php
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid


WORKDIR /var/www/html

COPY lamp-app-ecommerce .

EXPOSE 80

CMD ["/usr/sbin/apache2", "-D",  "FOREGROUND"]