version: '3.1'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    container_name: redis
    image: redis
    restart: always
  vote:
    container_name: vote
    image: vote:1.0.0
    restart: always
    ports:
      - 5000:80
    depends_on:
      - db
      - redis
  result:
    container_name: result
    image: result:1.0.0
    restart: always
    ports:
      - 8080:4000
    depends_on:
      - db
      - redis
  worker:
    container_name: worker
    image: worker:1.0.0
    restart: always
    depends_on:
      - redis
      - db